// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Day struct {
	ID     string `json:"id"`
	User   string `json:"user"`
	Date   int    `json:"date"`
	Emails int    `json:"emails"`
}

type User struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	ColorSchemeID int    `json:"colorSchemeID"`
}
