// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Day struct {
	ID     string `json:"id"`
	Date   string `json:"date"`
	Emails int    `json:"emails"`
}

type Token struct {
	ID           string    `json:"id"`
	AccessToken  string    `json:"access_token"`
	TokenType    string    `json:"token_type"`
	RefreshToken string    `json:"refresh_token"`
	Expiry       time.Time `json:"expiry"`
}

type User struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	ColorSchemeID int    `json:"colorSchemeID"`
}
